### ISSUE TITLE
Different vermagic

### ISSUE THREAD

**Issue by galdalali** [jetsonhacks/installACMModule#1]
Hey Jim,

I'm using TX2 connected to connect-tech Astro carrier board with kernel 4.4.38+.
The force option dose'nt work for me, it gives me the "version magic should be" error.
Is there any way you publish the pre-compiled cdc_acm?

Thanks, Gal

**Comment by jetsonhacks** [comment]
Not quite sure what you're looking for. The pre-compiled cdc-acm.ko file is in the repository.

**Comment by galdalali** [comment]
cdc-acm.ko is already compiled for 4.4.38-tegra. 
Before it was a driver (ko) it was a pre-compiled driver (c file for example). 
In order to solve the the issue of "version magic should be" I can do 2 things:
1. Compile the cdc-acm in my kernel with the vermagic 4.4.38+ .....
2. Compile the entire connect-tech kernel in order to change the string 4.4.38+ to 4.4.38-tegra (much more complicated)

**Comment by jetsonhacks** [comment]
Oh, there's a misunderstanding on the naming. 
The term pre-compiled means that the module has already been compiled.
You are asking for the source code for the module, cdc-acm.c
The file cdc-acm.c is available in the source code for the kernel and modules. You should be able to get it through the NVIDIA Embedded download site, or possibly through ConnectTech.

What command did you execute to force the module to load? It should only check the version (4.4.38) not the local version. Note that the module will only load if there's a CDC-ACM device attached.

**Comment by galdalali** [comment]
I used "sudo modprobe -f cdc-acm" and it gave me the error. CDC-ACM device was connected

**Comment by blairm-gmnameplate** [comment]
I am running into the same issue here. Was this ever resolved? (I'm relatively new to working in linux like this.)

**Comment by jetsonhacks** [comment]
@blairm-gmnameplate What issue are you running in to? What are carrier board are you running? Which version of L4T?

**Comment by blairm-gmnameplate** [comment]
Wow. Didn't expect to get a response so quickly. Thanks!

I am running a ConnectTech Rudi (ESG506-21) board. It is using a version of L4T28.1 (not sure exactly how custom it may be).  The kernel name (what shows up on a _uname -r query_) is 4.4.38+. 

When I run your script it recognizes the difference in names - I try to do the forcing but still get a "_Exec format error_" when I run _sudo modprobe -f cdc-acm_,  
I assume this error means that the kernel name missmatch is causing it to reject the module install.

I'm trying to come up with an easy installation solution for my customer, integrating my device (the one that should be using CDC-ACM) with their hardware (the TX2 system).

**Comment by jetsonhacks** [comment]
You can try to insmod it and see if that is a workaround. If you are providing this to a customer, you should compile the module with the correct version magic for your environment.

**Comment by blairm-gmnameplate** [comment]
I'm working now to recompile with the correct vermagic. I'll test that out and report back it if works. (Thanks for the help.)

**Comment by blairm-gmnameplate** [comment]
I recompiled L4T28.1 with the same vermagic name as my installed kernel. I copied the new compiled version of cdc-acm.ko into the installACMModule directory and successfully installed the module by running ./installCDCACM.sh.
The USB device I was attempting to get to load the cdc-acm driver now successfully reports as using the correct drivers.

**Comment by jetsonhacks** [comment]
Good to hear @blairm-gmnameplate
