### ISSUE TITLE
Still do not see ttyACM port

### ISSUE THREAD

**Issue by ArtlyStyles** [jetsonhacks/installACMModule#2]
I ran the scripe

nvidia@tegra-ubuntu:~/Downloads/installACMModule$ sudo ./installCDCACM.sh 
[sudo] password for nvidia: 
Kernel and Module Versions Match; Installing ...
'cdc-acm.ko' -> '/lib/modules/4.4.38-tegra/kernel/drivers/usb/class/cdc-acm.ko'
Installed cdc-acm Module

After that, I did a "lsusb", but I did not see anything related to the FOCBOX. 

When I ran BLDC tool, I did not see a ttyACM* connect either. How can I check if the ACM module is installed correctly?

**Comment by jetsonhacks** [comment]
Does the FOCBOX have power? Are you running L4T 28.1 or L4T 28.2?
