### ISSUE TITLE
What about L4T 28.2?

### ISSUE THREAD

**Issue by xoxota99** [jetsonhacks/installACMModule#3]
Does 28.2 also need drivers? Are these specific drivers "safe" to install for 28.2, or are they only good for 28.1?

**Comment by jetsonhacks** [comment]
These drivers are for L4T 28.1. 
L4T 28.2 has built in support for cdc-acm. I do not know about the other two.

**Comment by xoxota99** [comment]
Thanks!

**Comment by ghost** [comment]
Hey Jim, thanks for everything!

You wrote that

> These drivers are for L4T 28.1.
L4T 28.2 has built in support for cdc-acm. I do not know about the other two.

however when i type _lsmod_, i am not able to see cdc-acm module and when i type _lsusb_ i am not able to see my arduino but _QinHeng Electronics HL-340 USB-Serial adapter_. I appiled all the procedures in [https://www.jetsonhacks.com/2018/03/22/build-kernel-modules-nvidia-jetson-tx2-2/](url) but i still can not see my arduino device. Do you have any suggestions? Thanks..

**Comment by jetsonhacks** [comment]
You're welcome, I'm glad you have found it useful.

The HL-340 is a USB to serial converter, which is a part commonly substitute for the Arduinos FTDI chip, especially on clones. You will probably need a HL-340 driver depending on which version of L4T you are using. Depending on how its set to report, this may be indicating that this is the Arduino.

$ lsusb -t 

will print out which driver is associated with a given USB device.

**Comment by qiakeyufeiniao** [comment]
@jetsonhacks Hi, Jims, do you know Xavier Jetpack 4.1.1 already support USB to serial? I did not find related information online. I just want to confirm it before I buy an irobot create 2 to connect with Xavier.
